version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./config_duplicati:/config
      - /mnt/s3/backup/:/backups_s3
      - /mnt/backup/:/volokzhanin_backup
      - /home/volokzhanin/:/volokzhanin_home
    # ports:
    #   - 8200:8200
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external: true
    name: volokzhanin
